---
sidebar: sidebar 
permalink: concept_lic_platforms.html 
keywords: license, licensing, platform license offerings, license offerings, standard, premium, premium xl 
summary: ONTAP Selectの容量階層ライセンスまたは容量プールライセンスは、3つのプラットフォーム容量レベルのいずれかで購入できます。これらのライセンスによって、 ONTAP Selectを導入するホストの機能が決まります。 
---
= ONTAP Selectのプラットフォームライセンスについて学ぶ
:hardbreaks:
:allow-uri-read: 
:nofooter: 
:icons: font
:linkattrs: 
:imagesdir: ./media/


[role="lead"]
ONTAP Selectの容量階層または容量プールのライセンスは、標準、プレミアム、またはプレミアムXLレベルで購入できます。これらのライセンスによって、 ONTAP Selectを導入するホストの機能が決まります。



== プラットフォームライセンスが提供するもの

特定のライセンス オファリングは、次の 2 つの領域でハイパーバイザー ホストの機能を定義および制限します。

* インスタンスタイプ（CPU、メモリ）
* その他の機能


ライセンスは、StandardからPremium XLまで、機能の昇順で提供されています。通常、選択したライセンスオプションにより、そのレベルとそれより下位のすべてのレベルの機能が提供されます。例えば、Premiumレベルは、PremiumとStandardの両方の機能を利用できます。



== プラットフォームライセンスの提供

利用可能なプラットフォーム ライセンス オファリングは 3 つあります。



=== Standard

標準サービスでは、次の機能が提供されます。

* 小型インスタンスタイプのみ
* ハードディスクドライブ（HDD）のみ
* ローカルハードウェアRAIDコントローラのみ
* 仮想NAS




=== Premium

プレミアム オファリングでは、次の機能が提供されます。

* 小規模または中規模のインスタンスタイプ
* ハードディスクドライブ（HDD）またはソリッドステートドライブ（SSD）
* ローカルハードウェアRAIDコントローラまたはソフトウェアRAID
* 仮想NAS
* MetroCluster SDS




=== プレミアムXL

プレミアム XL オファリングでは、次の機能が提供されます。

* 小規模、中規模、大規模のインスタンスタイプ
* HDD、SSD、またはNVMeドライブ
* ローカルハードウェアRAIDコントローラまたはソフトウェアRAID
* 仮想NAS
* MetroCluster SDS



NOTE: SW-RAID 構成での大規模インスタンス タイプまたは NVMe ドライブの使用は、カーネルベースの仮想マシン (KVM) ではサポートされていません。



== プラットフォームライセンスオファリングのハードウェアサポートを比較する

標準、プレミアム、プレミアムXLライセンスは、幅広いハードウェアとソフトウェアをサポートしています。ハードウェアとソフトウェアのバージョンに関する最新情報については、 link:https://mysupport.netapp.com/matrix/["Interoperability Matrix Tool"^] 。

[role="tabbed-block"]
====
.コアアイテム
--
[cols="5"30"]
|===


2+| コアアイテムタイプ 3+| 説明 


2+| ホストプロトコル 3+| NFS、SMB/CIFS、iSCSI、NVMe over TCP 


2+| 展開オプション 3+| 単一ノード 2ノードクラスタ（HAペア） 4、6、または8ノードクラスタ 


2+| サポートされる容量（ノードあたり） 3+| 最大 400 TB の生データ (ESXi および KVM) 
|===
--
.ハードウェア
--
[cols="5"30"]
|===


2+| ハードウェアタイプ 3+| 説明 


2+| インスタンスサイズ | 小規模 | 中 | 大規模 


2+| CPUファミリー | Intel Xeon E5-26xx v3 (Haswell) 以降 | Intel Xeon E5-26xx v3 (Haswell) 以降 | Intel Xeon E5-26xx v3 (Haswell) 以降 


2+| ONTAP Select CPU / メモリ | 4 つの仮想 CPU (vCPU) / 16 GB の RAM | 8 個の vCPU / 64GB の RAM | 16 個の vCPU / 128 GB の RAM 


2+| ホストCPU / メモリの最小要件 ^1^ | 6コア / 24GBのRAM | 10コア / 72GBのRAM | 18コア / 136GBのRAM 


2+| ネットワーク（ノードあたり） 3+| 単一ノードクラスタの場合は最低2つの1GbEポート、2ノードクラスタ（HAペア）の場合は最低4つの1GbEポート、4、6、または8ノードクラスタの場合は最低2つの10GbEポート 
|===
^1^ ハイパーバイザーに 2 つのコアと 8Gb の RAM を想定しています。

--
.ストレージ タイプ
--
次の表は、指定されたストレージに必要な最小限のライセンス タイプを示しています。 

[cols="5"30"]
|===


2+| ストレージ タイプ 3+| 説明 


2+| ライセンス タイプ | Standard | Premium | プレミアムXL 


2+| インスタンスサイズ | 小規模 | 小型・中型 | 小、中、大 


2+| ハードウェア RAID コントローラを備えたローカル DAS | 8～60台のドライブ | 8～60台のドライブ | 8～60台のドライブ 


2+| HDD（SAS、NL-SAS、SATA） | 該当なし | 4～60台のドライブ | 4～60台のドライブ 


2+| SSD（SAS） | 該当なし | 4～60ドライブ（SSDのみ） | 4～60ドライブ（SSDのみ） 


2+| ソフトウェア RAID を備えたローカル DAS | 該当なし | 該当なし | 4～14 ドライブ（NVMe のみ） 


2+| 外部配列 ^1^ 3+| 外部アレイにホストされるデータストアは、FC、FCoE、iSCSI、NFS（KVMではNFSはサポートされていません）を介して接続されます。これらのデータストアは、高い可用性と耐障害性を提供します。 
|===
^1^ 外部アレイ プロトコルのサポートは、ネットワーク ストレージの接続を反映します。

--
.ソフトウェア
--
[cols="5"30"]
|===


2+| ソフトウェアの種類 3+| 説明 


2+| ハイパーバイザーのサポート (VMware) 3+| VMware vSphere 7.0GA およびアップデート 1 ～ 3C VMware vSphere 8.0GA およびアップデート 1 ～ 3 


2+| ハイパーバイザーサポート (KVM) 3+| RedHat Enterprise Linux 64 ビット (KVM) 9.5、9.4、9.3、9.2、9.1、9.0、8.9、8.8、8.7、および 8.6 Rocky Linux (KVM) 9 および 8 


2+| 管理ソフトウェア 3+| NetApp Active IQ Unified Manager管理スイートONTAP Select Deploy Utility SnapCenter (オプション) 
|===
--
====
.関連情報
link:concept_lic_production.html["容量層と容量プールのライセンスの種類について学ぶ"] 。
