---
sidebar: sidebar 
permalink: reference_plan_ots_two_node.html 
keywords: plan, planning, two nodes, two node clusters 
summary: HA 構成の 2 ノード クラスタの導入には、他のクラスタ ノード構成と同様の計画と設定が必要です。ただし、2 ノード クラスタを作成する際には、いくつかの違いに注意する必要があります。 
---
= ONTAP Select 2ノードクラスタ（HA搭載）
:hardbreaks:
:allow-uri-read: 
:nofooter: 
:icons: font
:linkattrs: 
:imagesdir: ./media/


[role="lead"]
HA 構成の 2 ノード クラスタの導入には、他のクラスタ ノード構成と同様の計画と設定が必要です。ただし、2 ノード クラスタを作成する際には、いくつかの違いに注意する必要があります。

.対象環境
2 ノード クラスターは 1 つの HA ペアで構成され、リモート オフィスおよびブランチ オフィスの展開用に特別に設計されています。


NOTE: 主にリモートおよびブランチ オフィス環境向けに設計されていますが、必要に応じてデータ センターに 2 ノード クラスターを展開することもできます。

.ライセンス
2ノードクラスタは、VMware vSphereライセンスを使用して導入できます。ただし、VMware ROBO StandardおよびAdvancedライセンスは、リモートオフィスやブランチオフィスへの導入に最適です。

.仲介サービス
クラスタが2つのノードで構成されている場合、ノードに障害が発生したり通信が途絶えたりすると、必要なクォーラムを達成できなくなります。このようなスプリットブレイン状態を解決するために、 ONTAP Select Deployユーティリティのすべてのインスタンスにはメディエータサービスが含まれています。このサービスは、アクティブな2ノードクラスタの各ノードに接続し、HAペアを監視して障害管理を支援します。メディエータサービスは、各2ノードクラスタに関連付けられた専用のiSCSIターゲットでHAの状態情報を維持します。


CAUTION: アクティブな2ノードクラスタが1つ以上ある場合、クラスタを管理するONTAP Select Deploy仮想マシンは常に実行されている必要があります。Deploy仮想マシンが停止または障害が発生した場合、メディエーターサービスは利用できなくなり、2ノードクラスタのHA機能が失われます。

.クラスターとメディエーターサービスの場所
2ノードクラスタは通常、リモートオフィスまたはブランチオフィスに導入されるため、企業のデータセンターや管理サポートを提供するDeployユーティリティから離れた場所に配置できます。この構成では、Deployユーティリティとクラスタ間の管理トラフィックはWAN経由で送信されます。制限事項の詳細については、リリースノートをご覧ください。

.デプロイ構成データをバックアップする
ベストプラクティスとして、クラスター作成後も含め、定期的にデプロイ構成データをバックアップすることをお勧めします。これは、バックアップにメディエーター構成データが含まれるため、2ノードクラスターでは特に重要になります。

.デプロイに割り当てられた静的IPアドレス
Deploy管理ユーティリティには静的IPアドレスを割り当てる必要があります。この要件は、1つ以上のONTAP Select 2ノードクラスタを管理するすべてのDeployインスタンスに適用されます。
