---
sidebar: sidebar 
permalink: task_cli_deploy_recover_two_node.html 
keywords: administer, administering, cli, two node cluster, recover, recovering 
summary: ONTAP Select Deployユーティリティに障害が発生したり、何らかの理由で使用できなくなったりした場合、 ONTAP Selectノードおよびクラスタを管理できなくなります。さらに、Deployに含まれるメディエーターサービスが利用できなくなるため、すべての2ノードクラスタでHA機能が失われます。回復不能な障害が発生した場合は、管理機能とHA機能を復元するために、Deployユーティリティインスタンスをリカバリする必要があります。 
---
= 2ノードクラスタのONTAP Select Deployユーティリティをリカバリする
:hardbreaks:
:allow-uri-read: 
:nofooter: 
:icons: font
:linkattrs: 
:imagesdir: ./media/


[role="lead"]
ONTAP Select Deployユーティリティに障害が発生したり、何らかの理由で使用できなくなったりした場合、 ONTAP Selectノードおよびクラスタを管理できなくなります。さらに、Deployに含まれるメディエーターサービスが利用できなくなるため、すべての2ノードクラスタでHA機能が失われます。回復不能な障害が発生した場合は、管理機能とHA機能を復元するために、Deployユーティリティインスタンスをリカバリする必要があります。



== 開始する前に

成功を確実にするために、デプロイ ユーティリティのインスタンスの回復を試みる前に準備する必要があります。

.必要なスキルと情報
いくつかの管理手順に精通し、必要な情報を把握している必要があります。

.Deploy仮想マシンのインストール
ハイパーバイザー環境にONTAP Select Deploy ユーティリティの新しいインスタンスをインストールできる必要があります。

.ONTAPコマンドライン インターフェイス
ONTAP SelectクラスタのONTAP CLI にサインインし、シェル インターフェイスを使用できる必要があります。

.デプロイユーティリティ構成のバックアップの可用性
ONTAP Selectの2ノードクラスタを含む、障害が発生したDeployユーティリティインスタンスの構成データのバックアップがあるかどうかを確認する必要があります。クラスタが含まれていないバックアップがある可能性があります。

.デプロイ構成のバックアップの復元
使用した回復手順に応じて、デプロイ構成データのバックアップを復元できるはずです。

.元のデプロイ仮想マシンのIPアドレス
障害が発生した元の Deploy ユーティリティ仮想マシンの IP アドレスを知っておく必要があります。

.ストレージ容量ライセンス
容量プールライセンスと容量階層ライセンスのどちらを使用するかを決定する必要があります。容量プールライセンスを使用する場合は、デプロイインスタンスを復旧またはリストアした後、各容量プールライセンスを再インストールする必要があります。

.どの回復手順を使用するかを決定する
ONTAP Select Deployユーティリティのインスタンスをリカバリする際に使用する手順を決定する必要があります。この決定は、 ONTAP Selectの2ノードクラスタを含む、障害が発生した元のDeployユーティリティの設定データのバックアップがあるかどうかに基づいて行われます。

[cols="35,65"]
|===
| 2 ノード クラスターを含む Deploy バックアップはありますか? | 使用する回復手順 


| はい | 構成バックアップを使用してデプロイユーティリティインスタンスを復元する 


| いいえ | デプロイユーティリティインスタンスを再構成して回復する 
|===


== 構成バックアップを使用してデプロイユーティリティインスタンスを復元する

2ノードクラスタを含む、障害が発生したDeployユーティリティインスタンスのバックアップがある場合は、構成データを新しいDeploy仮想マシンインスタンスにリストアできます。その後、 ONTAP Selectクラスタ内の2つのノードに対して追加の構成を実行して、リカバリを完了する必要があります。

.開始する前に
2ノードクラスタを含む、障害が発生した元のDeploy仮想マシンの構成データのバックアップが必要です。2ノードクラスタのONTAP CLIにサインインでき、2つのノードのONTAP名を把握している必要があります。

.タスク概要
復元する構成バックアップには 2 ノード クラスターが含まれているため、メディエーター iSCSI ターゲットとメールボックスは新しい Deploy ユーティリティ仮想マシンに再作成されます。

.手順
. ONTAP Select Deploy ユーティリティの新しいインスタンスを準備します。
+
.. 新しい Deploy ユーティリティ仮想マシンをインストールします。
.. 以前のバックアップから新しい仮想マシンにデプロイ構成を復元します。
+
インストールおよび復元手順の詳細については、関連タスクを参照してください。



. ONTAP Select 2 ノード クラスタのONTAPコマンドライン インターフェイスにSign in。
. advanced権限モードに切り替えます。
+
`set adv`

. 新しい Deploy 仮想マシンの IP アドレスが元の Deploy 仮想マシンの IP アドレスと異なる場合は、古いメディエーター iSCSI ターゲットを削除し、新しいターゲットを追加する必要があります。
+
....
storage iscsi-initiator remove-target -node * -target-type mailbox

storage iscsi-initiator add-target -node <node1_name> -label mediator -target-type mailbox -target-portal <ip_address> -target-name <target>

storage iscsi-initiator add-target -node <node2_name> -label mediator -target-type mailbox -target-portal <ip_address> -target-name <target>
....
+
その `<ip_address>`パラメータは、新しいデプロイ仮想マシンの IP アドレスです。

+
これらのコマンドにより、 ONTAP Selectノードは新しい Deploy ユーティリティ仮想マシン上のメールボックス ディスクを検出できるようになります。

. メディエーター ディスクの名前を決定します。
+
`disk show -container-type mediator`

. メールボックス ディスクを 2 つのノードに割り当てます。
+
....
disk assign -disk <mediator-disk1-name> -owner <node1-name>
disk assign -disk <mediator-disk2-name> -owner <node2-name>
....
. ストレージ フェイルオーバーが有効になっていることを確認します。
+
`storage failover show`



.終了後の操作
容量プールライセンスをご利用の場合は、各容量プールライセンスを再インストールする必要があります。詳細については、「容量プールライセンスの再インストール」をご覧ください。



== デプロイユーティリティインスタンスを再構成して回復する

2ノードクラスタを含む、障害が発生したDeployユーティリティインスタンスのバックアップがない場合は、新しいDeploy仮想マシンでメディエータiSCSIターゲットとメールボックスを設定する必要があります。その後、 ONTAP Selectクラスタ内の2つのノードに対して追加の設定を行い、リカバリを完了する必要があります。

.開始する前に
新しいDeployユーティリティインスタンスのメディエーターターゲットの名前が必要です。2ノードクラスタのONTAP CLIにサインインでき、2つのノードのONTAP名を知っている必要があります。

.タスク概要
2ノードクラスタが含まれていない場合でも、必要に応じて構成バックアップを新しいDeploy仮想マシンにリストアできます。リストアでは2ノードクラスタは再作成されないため、DeployのONTAP SelectオンラインドキュメントWebページから、メディエーターiSCSIターゲットとメールボックスを新しいDeployユーティリティインスタンスに手動で追加する必要があります。2ノードクラスタにサインインでき、2つのノードのONTAP名を知っている必要があります。


NOTE: リカバリ手順の目的は、2 ノード クラスターを正常な状態に復元し、通常の HA テイクオーバーおよびギブバック操作を実行できるようにすることです。

.手順
. ONTAP Select Deploy ユーティリティの新しいインスタンスを準備します。
+
.. 新しい Deploy ユーティリティ仮想マシンをインストールします。
.. 必要に応じて、以前のバックアップから新しい仮想マシンにデプロイ構成を復元します。
+
以前のバックアップを復元した場合、新しいDeployインスタンスには2ノードクラスタは含まれません。インストールと復元の手順の詳細については、関連情報セクションを参照してください。



. ONTAP Select 2 ノード クラスタのONTAPコマンドライン インターフェイスにSign in。
. 高度な特権モードに入る:
+
`set adv`

. メディエーターの iSCSI ターゲット名を取得します。
+
`storage iscsi-initiator show -target-type mailbox`

. 新しい Deploy ユーティリティ仮想マシンのオンライン ドキュメント Web ページにアクセスし、管理者アカウントを使用してサインインします。
+
`\http://<ip_address>/api/ui`

+
デプロイ仮想マシンの IP アドレスを使用する必要があります。

. *Mediator* をクリックし、次に *GET /mediators* をクリックします。
. *試してみる*をクリックすると、デプロイによって管理されているメディエーターのリストが表示されます。
+
必要なメディエーター インスタンスの ID をメモします。

. *Mediator* をクリックし、次に *POST* をクリックします。
. mediator_id の値を指定します。
. の横にある*モデル*をクリックします `iscsi_target`名前の値を完了します。
+
iqn_name パラメータにはターゲット名を使用します。

. *試してみる* をクリックして、メディエーター iSCSI ターゲットを作成します。
+
リクエストが成功すると、HTTP ステータス コード 200 が返されます。

. 新しい Deploy 仮想マシンの IP アドレスが元の Deploy 仮想マシンの IP アドレスと異なる場合は、 ONTAP CLI を使用して古いメディエータ iSCSI ターゲットを削除し、新しいターゲットを追加する必要があります。
+
....
storage iscsi-initiator remove-target -node * -target-type mailbox

storage iscsi-initiator add-target -node <node1_name> -label mediator -target-type mailbox -target-portal <ip_address> -target-name <target>

storage iscsi-initiator add-target -node <node2_name> -label mediator-target-type mailbox -target-portal <ip_address> -target-name <target>
....
+
その `<ip_address>`パラメータは、新しいデプロイ仮想マシンの IP アドレスです。



これらのコマンドにより、 ONTAP Selectノードは新しい Deploy ユーティリティ仮想マシン上のメールボックス ディスクを検出できるようになります。

. メディエーター ディスクの名前を決定します。
+
`disk show -container-type mediator`

. メールボックス ディスクを 2 つのノードに割り当てます。
+
....
disk assign -disk <mediator-disk1-name> -owner <node1-name>

disk assign -disk <mediator-disk2-name> -owner <node2-name>
....
. ストレージ フェイルオーバーが有効になっていることを確認します。
+
`storage failover show`



.終了後の操作
容量プールライセンスを使用する場合は、各容量プールライセンスを再インストールする必要があります。詳細については、「容量プールライセンスの再インストール」をご覧ください。

.関連情報
* link:task_install_deploy.html["ONTAP Select Deploy をインストールする"]
* link:task_cli_migrate_deploy.html#restoring-the-deploy-configuration-data-to-the-new-virtual-machine["デプロイ構成データを新しい仮想マシンに復元します"]
* link:task_adm_licenses.html#reinstalling-a-capacity-pool-license["容量プールライセンスを再インストールする"]

