---
sidebar: sidebar 
permalink: task_cli_upgrade_deploy.html 
keywords: administer, administering, cli, deploy, upgrade deploy 
summary: コマンドライン インターフェイスを使用して、既存の Deploy ユーティリティ仮想マシンをインプレースでアップグレードできます。 
---
= ONTAP Select Deployインスタンスをアップグレードする
:hardbreaks:
:allow-uri-read: 
:nofooter: 
:icons: font
:linkattrs: 
:imagesdir: ./media/


[role="lead"]
コマンドライン インターフェイスを使用して、既存の Deploy ユーティリティ仮想マシンをインプレースでアップグレードできます。



== 開始する前に

アップグレード中は、Deploy ユーティリティを使用して他のタスクを実行しないでください。Deployユーティリティのアップグレードに関する情報と制限については、最新のリリースノートを参照してください。


NOTE: ONTAP Select Deploy管理ユーティリティの古いインスタンスがインストールされている場合は、最新リリースにアップグレードする必要があります。ONTAPONTAP SelectノードとONTAP Select Deployコンポーネントは個別にアップグレードされます。 link:concept_adm_upgrading_nodes.html["ONTAP Selectノードをアップグレードする"^]詳細についてはこちらをご覧ください。



== アップグレードパッケージをダウンロードする

アップグレード プロセスを開始するには、NetAppサポート サイトから適切なDeploy仮想マシン アップグレード ファイルをダウンロードする必要があります。アップグレード パッケージは、単一の圧縮ファイルとしてフォーマットされます。

.手順
. アクセスlink:https://mysupport.netapp.com/site/["NetAppサポート サイト"^] Web ブラウザを使用して、[ダウンロード] メニューから [*ダウンロード*] を選択します。
. 下にスクロールして* ONTAP Select Deploy Upgrade*を選択します。
. アップグレード パッケージの希望するリリースを選択します。
. エンド ユーザー ライセンス契約 (EULA) を確認し、[同意して続行] を選択します。
. 環境に応じて必要に応じてすべてのプロンプトに応答し、適切なパッケージを選択してダウンロードします。




== パッケージをデプロイ仮想マシンにアップロードします

アップグレード パッケージを取得したら、そのファイルを Deploy 仮想マシンにアップロードする必要があります。

.開始する前に
アップグレードファイルはローカルワークステーション上に用意されている必要があります。また、管理者ユーザーアカウントのパスワードも必要です。

.このタスクについて
このタスクでは、Deploy仮想マシンにファイルをアップロードする方法の一つを説明します。環境によっては、より適切な他の方法がある場合があります。

.手順
. ローカル ワークステーションのコマンド シェルで、scp ユーティリティを使用して、イメージ ファイルを Deploy 仮想マシンにアップロードします。
+
例

+
....
scp ONTAPdeploy2.12_upgrade.tar.gz admin@10.228.162.221:/home/admin (provide password when prompted)
....


.結果
アップグレード ファイルは、管理者ユーザーのホーム ディレクトリに保存されます。



== アップグレードパッケージを適用する

アップグレード ファイルが Deploy 仮想マシンにアップロードされたら、アップグレードを適用できます。

.開始する前に
Deployユーティリティ仮想マシンのどのディレクトリにアップグレードファイルが配置されているかを確認する必要があります。また、アップグレードの実行中は、Deployユーティリティを使用して他のタスクを実行しないでください。

.手順
. 管理者アカウントで SSH を使用して、デプロイ ユーティリティ CLI にSign in。
. 適切なディレクトリ パスとファイル名を使用してアップグレードを実行します。
+
`deploy upgrade -package-path FILEPATH`

+
例

+
....
deploy upgrade -package-path /home/admin/ONTAPdeploy2.12_upgrade.tar.gz
....


.終了後の操作
アップグレード手順が完了する前に、Deploy仮想マシン構成のバックアップを作成するように求められます。また、新しく作成されたDeployページを表示できるように、ブラウザのキャッシュをクリアする必要があります。
