---
sidebar: sidebar 
permalink: task_cli_deploy_image_add.html 
keywords: administer, administering, cli, deploy, ontap select image, add 
summary: ONTAP Select イメージを Deploy 管理ユーティリティのインスタンスに追加できます。イメージをインストールしたら、 ONTAP Select クラスタの導入時に使用できます。 
---
= ONTAP Selectイメージをデプロイに追加する
:hardbreaks:
:allow-uri-read: 
:nofooter: 
:icons: font
:linkattrs: 
:imagesdir: ./media/


[role="lead"]
ONTAP Select イメージを Deploy 管理ユーティリティのインスタンスに追加できます。イメージをインストールしたら、 ONTAP Select クラスタの導入時に使用できます。



== 開始する前に

大まかに言うと、ONTAP Select イメージを Deploy のインスタンスに追加するプロセスは、次の 4 つのステップで構成されます：

. インストールイメージのダウンロード
. インストールイメージを Deploy 仮想マシンにアップロードする
. インストールイメージの追加
. 利用可能なインストールイメージを表示する


新しいONTAP Selectイメージを Deploy に追加する前に、まず不要なイメージを削除する必要があります。


NOTE: Deployユーティリティのインスタンスに含まれている元のバージョンよりも前のバージョンのONTAP Selectイメージのみを追加してください。NetAppNetApp提供される新しいバージョンのONTAP Selectを追加することは、サポートされていない構成です。



== インストールイメージをダウンロードする

ONTAP SelectイメージをDeployユーティリティのインスタンスに追加するプロセスを開始するには、 NetAppサポートサイトからインストールイメージをダウンロードする必要があります。ONTAPONTAP Selectインストールイメージは、単一の圧縮ファイルとしてフォーマットされています。

.手順
. Web ブラウザーを使用してNetApp Support Siteにアクセスし、*Support Quick Links*をクリックします。
. * トップタスク * の下にある * ソフトウェアのダウンロード * をクリックし、サイトにサインインします。
. *製品を探す* をクリックします。
. 下にスクロールして*ONTAP Select*をクリックします。
. *Other Available Select Software* で、 *Deploy Upgrade, Node Upgrade, Image Install* をクリックします。
. アップグレード パッケージの目的のリリースを選択します。
. エンドユーザーライセンス契約（EULA）を確認し、*Accept & Continue*をクリックします。
. 適切なパッケージを選択してダウンロードし、環境に応じて必要なすべてのプロンプトに応答します。




== インストールイメージをDeployにアップロードする

ONTAP Selectインストール イメージを取得したら、そのファイルを Deploy 仮想マシンにアップロードする必要があります。

.開始する前に
ローカル ワークステーションにインストール イメージ ファイルを用意しておく必要があります。Deploy 管理者ユーザー アカウントのパスワードも必要です。

.タスク概要
このタスクでは、Deploy仮想マシンにファイルをアップロードする方法の一つを説明します。環境によっては、より適切な他の方法がある場合があります。

.手順
. ローカル ワークステーションのコマンド シェルで、イメージ ファイルを Deploy 仮想マシンにアップロードします。
+
例

+
....
scp image_v_93_install_esx.tgz admin@10.234.81.101:/home/admin (provide password when prompted)
....
+
例

+
....
sftp admin@10.234.81.101 (provide password when prompted)
put image_v_93_install_esx.tgz
exit
....


.結果
ノードインストールファイルは、管理者ユーザーのホームディレクトリに保存されます。



== インストールイメージを追加する

新しいクラスタの導入時に使用できるように、ONTAP Select インストールイメージを Deploy images ディレクトリに追加できます。

.開始する前に
インストールイメージファイルがDeployユーティリティ仮想マシンのどのディレクトリに配置されているかを確認する必要があります。ファイルは管理者のホームディレクトリにあるものと想定されます。

.手順
. 管理者 (admin) アカウントで SSH を使用して、デプロイ ユーティリティ CLI にSign in。
. Bash シェルを起動します。
+
`shell bash`

. インストール イメージ ファイルを images ディレクトリに配置します。
+
例
`tar -xf image_v_93_install_esx.tgz -C /opt/netapp/images/`





== 利用可能なインストールイメージを表示する

新しいクラスターをデプロイするときに使用できる ONTAP Select イメージを表示できます。

.手順
. デプロイ ユーティリティ仮想マシンのオンライン ドキュメント Web ページにアクセスし、管理者 (admin) アカウントを使用してサインインします。
+
`\http://<FQDN|IP_ADDRESS>/api/ui`

+
デプロイ仮想マシンのドメイン名または IP アドレスを使用します。

. ページの下部に移動して*Deploy*をクリックし、*GET /images*をクリックします。
. *試してみる！*をクリックすると、利用可能なONTAP Selectイメージが表示されます。
. 希望する画像が利用可能であることを確認します。

