---
sidebar: sidebar 
permalink: task_cli_upgrade_deploy.html 
keywords: administer, administering, cli, deploy, upgrade deploy 
summary: コマンドライン インターフェイスを使用して、既存の Deploy ユーティリティ仮想マシンをインプレースでアップグレードできます。 
---
= ONTAP Select Deployインスタンスをアップグレードする
:hardbreaks:
:allow-uri-read: 
:nofooter: 
:icons: font
:linkattrs: 
:imagesdir: ./media/


[role="lead"]
ONTAP Select Deploy ユーティリティ CLI を使用して、既存の ONTAP Select Deploy ユーティリティ仮想マシンをインプレースでアップグレードします。

.開始する前に
アップグレード中に ONTAP Select Deploy が他のタスクの実行に使用されていないことを確認します。ONTAP Select Deploy ユーティリティのアップグレードに関する情報と制限事項については、link:reference_release_notes.html["リリース ノート"]を参照してください。


NOTE: ONTAP Select Deploy管理ユーティリティの古いインスタンスがインストールされている場合は、最新リリースにアップグレードする必要があります。ONTAPONTAP SelectノードとONTAP Select Deployコンポーネントは個別にアップグレードされます。 link:concept_adm_upgrading_nodes.html["ONTAP Selectノードをアップグレードする"^]詳細についてはこちらをご覧ください。



== ステップ1：アップグレードパッケージをダウンロードする

アップグレードプロセスを開始するには、NetApp Support SiteからONTAP Select Deployアップグレードファイルをダウンロードします。アップグレードパッケージは、単一の圧縮ファイルとしてフォーマットされます。

.手順
. link:https://mysupport.netapp.com/site/downloads/["NetApp Support Site ダウンロード"^]ページにアクセスします。
. 下にスクロールして*ONTAP Select Deploy*を選択してください。
. 希望する ONTAP Select バージョンを選択してください。
. エンド ユーザー ライセンス契約 (EULA) を確認し、[同意して続行] を選択します。
. 適切な*ONTAP Select Deploy Upgrade*パッケージを選択してダウンロードします。必要に応じてすべてのプロンプトに応答します。




== ステップ2：パッケージをONTAP Select Deploy仮想マシンにアップロードする

パッケージをダウンロードしたら、ONTAP Select Deploy仮想マシンにファイルをアップロードする必要があります。

.開始する前に
* アップグレード ファイルがローカル ワークステーションで使用可能であることを確認します。
* 管理者ユーザーアカウントのパスワードがあることを確認します。


.タスク概要
このタスクでは、ONTAP Select Deploy仮想マシンにファイルをアップロードする1つの方法について説明します。ご使用の環境により適した他のオプションがある可能性があります。

.手順
. ローカルワークステーションのコマンドシェルで、 `scp`（Secure Copy Protocol）ユーティリティを使用して、次の例に示すように、画像ファイルをONTAP Select Deploy仮想マシンにアップロードします：
+
....
scp ONTAPdeploy2.12_upgrade.tar.gz admin@10.228.162.221:/home/admin (provide password when prompted)
....


.結果
アップグレード ファイルは、管理者ユーザーのホーム ディレクトリに保存されます。



== ステップ3：アップグレードパッケージを適用する

アップグレードファイルをONTAP Select Deploy仮想マシンにアップロードした後、アップグレードを適用できます。

.開始する前に
* ONTAP Select Deploy ユーティリティ仮想マシンで、アップグレードファイルが配置されているディレクトリを確認します。
* アップグレードの実行中は、ONTAP Select Deployが他のタスクの実行に使用されていないことを確認してください。


.手順
. 管理者アカウントで SSH を使用して ONTAP Select Deploy ユーティリティ CLI に Sign in します。
. 適切なディレクトリ パスとファイル名を使用してアップグレードを実行します。
+
[source, cli]
----
deploy upgrade -package-path <file_path>
----
+
コマンド例：

+
....
deploy upgrade -package-path /home/admin/ONTAPdeploy2.12_upgrade.tar.gz
....


.終了後の操作
アップグレード手順が完了する前に、ONTAP Select Deploy仮想マシン構成のバックアップを作成するように求められます。また、新しく作成されたONTAP Select Deployページを表示するには、ブラウザのキャッシュをクリアする必要があります。
