---
sidebar: sidebar 
permalink: task_cli_deploy_image_add.html 
keywords: administer, administering, cli, deploy, ontap select image, add 
summary: ONTAP Select イメージを Deploy 管理ユーティリティのインスタンスに追加します。インストール後、ONTAP Selectクラスタの導入時に使用できます。 
---
= ONTAP Selectイメージをデプロイに追加する
:hardbreaks:
:allow-uri-read: 
:nofooter: 
:icons: font
:linkattrs: 
:imagesdir: ./media/


[role="lead"]
ONTAP Select イメージを Deploy 管理ユーティリティのインスタンスに追加します。イメージをインストールしたら、ONTAP Select クラスタの導入時に使用できます。

.開始する前に
新しいONTAP Selectイメージを Deploy に追加する前に、まず不要なイメージを削除する必要があります。


NOTE: Deployユーティリティのインスタンスに含まれている元のバージョンよりも前のバージョンのONTAP Selectイメージのみを追加してください。NetAppNetApp提供される新しいバージョンのONTAP Selectを追加することは、サポートされていない構成です。



== ステップ1：インストールイメージをダウンロードする

ONTAP SelectイメージをDeployユーティリティのインスタンスに追加するプロセスを開始するには、 NetAppサポートサイトからインストールイメージをダウンロードする必要があります。ONTAPONTAP Selectインストールイメージは、単一の圧縮ファイルとしてフォーマットされています。

.手順
. link:https://mysupport.netapp.com/site/downloads/["NetApp Support Site ダウンロード"^]ページにアクセスします。
. 下にスクロールして、* ONTAP Select Image *を選択します。
. インストールイメージの目的のリリースを選択します。
. エンド ユーザー ライセンス契約 (EULA) を確認し、[同意して続行] を選択します。
. 適切な*ONTAP Select Image Install*パッケージを選択してダウンロードしてください。必要に応じてすべてのプロンプトに応答します。




== ステップ2：インストールイメージをDeployにアップロードする

ONTAP Selectインストール イメージを取得したら、そのファイルを Deploy 仮想マシンにアップロードする必要があります。

.開始する前に
ローカルワークステーションにインストールイメージファイルがあることを確認します。Deploy管理者ユーザーアカウントのパスワードも必要です。

.タスク概要
このタスクでは、Deploy仮想マシンにファイルをアップロードする方法の一つを説明します。環境によっては、より適切な他の方法がある場合があります。

.手順
. ローカル ワークステーションのコマンド シェルで、次の例に示すように、イメージ ファイルを Deploy 仮想マシンにアップロードします：
+
....
scp image_v_93_install_esx.tgz admin@10.234.81.101:/home/admin (provide password when prompted)
....
+
....
sftp admin@10.234.81.101 (provide password when prompted)
put image_v_93_install_esx.tgz
exit
....


.結果
ノードインストールファイルは、管理者ユーザーのホームディレクトリに保存されます。



== ステップ3：インストールイメージを追加する

新しいクラスタを導入する際に使用できるように、ONTAP Select インストールイメージを Deploy images ディレクトリに追加します。

.開始する前に
インストールイメージファイルがDeployユーティリティ仮想マシンのどのディレクトリに配置されているかを確認する必要があります。ファイルは管理者のホームディレクトリにあるものと想定されます。

.手順
. 管理者 (admin) アカウントで SSH を使用して、デプロイ ユーティリティ CLI にSign in。
. Bash シェルを起動します。
+
[source, cli]
----
shell bash
----
. 次の例に示すように、インストールイメージファイルを images ディレクトリに配置します：
+
`tar -xf image_v_93_install_esx.tgz -C /opt/netapp/images/`





== ステップ4：利用可能なインストールイメージを表示する

新しいクラスタを導入する際に使用可能な ONTAP Select イメージを表示します。

.手順
. デプロイ ユーティリティ仮想マシンのオンライン ドキュメント Web ページにアクセスし、管理者 (admin) アカウントを使用してサインインします。
+
`\http://<FQDN|IP_ADDRESS>/api/ui`

+
デプロイ仮想マシンのドメイン名または IP アドレスを使用します。

. ページの下部に移動して *Deploy* を選択し、次に *GET /images* を選択します。
. *試してみる！*を選択すると、利用可能なONTAP Selectイメージが表示されます。
. 希望する画像が利用可能であることを確認します。

